spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      connection:
        characterEncoding=utf-8
        CharSet=utf-8
        useUnicode=true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  mail:
    host: smtp.yandex.ru
    username: uw@dru.su
    password: 1234
    port: 465
    protocol: smtps


